### ISSUE TITLE
Doesn't work with 1.10 + Python 3 out-of-the-box

### ISSUE THREAD

**Issue by kibertoad** [mshytikov/airflow-dev-env#4]
When DAG is executed, this https://github.com/sdispater/pendulum/issues/267 happens

**Comment by kibertoad** [comment]
@mshytikov I would recommend locking to "apache-airflow==1.9.0" explicitly to make sure that this project is working out-of-the-box.

**Comment by mshytikov** [comment]
migrated to latest airflow version see #5
